server:
  port: 38080

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: gorae_user
            predicates:
              -Path=/api/user/**
            url: lb://gorae-user
          - id: gorae_post
            predicates:
              -Path=/api/post/**
            url: lb://gorae-post
          - id: gorae_notification
            predicates:
              -Path=/api/answers/**
            url: lb://gorae-notification
          - id: gorae_leaderboard
            predicates:
              -Path=/api/leaderboard/**
            url: lb://gorae-leaderboard
