server:
  port: 38080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: gorae-user
            uri: http://localhost:8080
            predicates:
              - Path=/api/user/**
            filters:
              - name: addAuthenticationHeader
          - id: gorae-post
            uri: http://localhost:8081
            predicates:
              - Path=/api/post/**
            filters:
              - name: addAuthenticationHeader
          - id: gorae-notification
            uri: http://localhost:8082
            predicates:
              - Path=/api/notification/**
            filters:
              - name: addAuthenticationHeader
          - id: gorae-leaderboard
            uri: http://localhost:8083
            predicates:
              - Path=/api/leaderboard/**
            filters:
              - name: addAuthenticationHeader

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG


jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdtossoiseeTG764Gdslkj298GsdachsisddogaeWg86G