server:
  port: 38080

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdtossoiseeTG764Gdslkj298GsdachsisddogaeWg86G

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: gorae-user
            predicates:
              - Path=/api/user/**
            uri: http://localhost:8080
          - id: gorae-post
            predicates:
              - Path=/api/post/**
            uri: http://gorae-post
          - id: gorae-notification
            predicates:
              - Path=/api/answers/**
            uri: http://gorae-notification
          - id: gorae-leaderboard
            predicates:
              - Path=/api/leaderboard/**
            uri: http://gorae-leaderboard
